# https://goframe.org/docs/web/server-config-file-template
server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

# https://goframe.org/docs/core/glog-config
logger:
  level : "all"
  stdout: true

# https://goframe.org/docs/core/gdb-config-file
database:
  default:
    type: "mysql"
    host: "127.0.0.1"
    port: "3307"
    user: "poker"
    pass: "poker123456"
    name: "app"
    charset: "utf8mb4"
    timezone: "Local"

# https://goframe.org/docs/core/gredis-config
redis:
  default:
    address: 127.0.0.1:6379
    pass:    redis123456
    db:      0