// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"claude-test/internal/dao/internal"
)

// buyinRecordsDao is the data access object for the table buyin_records.
// You can define custom methods on it to extend its functionality as needed.
type buyinRecordsDao struct {
	*internal.BuyinRecordsDao
}

var (
	// BuyinRecords is a globally accessible object for table buyin_records operations.
	BuyinRecords = buyinRecordsDao{internal.NewBuyinRecordsDao()}
)

// Add your custom methods and functionality below.
