// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"claude-test/internal/dao/internal"
)

// chipTransactionsDao is the data access object for the table chip_transactions.
// You can define custom methods on it to extend its functionality as needed.
type chipTransactionsDao struct {
	*internal.ChipTransactionsDao
}

var (
	// ChipTransactions is a globally accessible object for table chip_transactions operations.
	ChipTransactions = chipTransactionsDao{internal.NewChipTransactionsDao()}
)

// Add your custom methods and functionality below.
