// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"claude-test/internal/dao/internal"
)

// clubMembersDao is the data access object for the table club_members.
// You can define custom methods on it to extend its functionality as needed.
type clubMembersDao struct {
	*internal.ClubMembersDao
}

var (
	// ClubMembers is a globally accessible object for table club_members operations.
	ClubMembers = clubMembersDao{internal.NewClubMembersDao()}
)

// Add your custom methods and functionality below.
