// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"claude-test/internal/dao/internal"
)

// clubsDao is the data access object for the table clubs.
// You can define custom methods on it to extend its functionality as needed.
type clubsDao struct {
	*internal.ClubsDao
}

var (
	// Clubs is a globally accessible object for table clubs operations.
	Clubs = clubsDao{internal.NewClubsDao()}
)

// Add your custom methods and functionality below.
