// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"claude-test/internal/dao/internal"
)

// gamesDao is the data access object for the table games.
// You can define custom methods on it to extend its functionality as needed.
type gamesDao struct {
	*internal.GamesDao
}

var (
	// Games is a globally accessible object for table games operations.
	Games = gamesDao{internal.NewGamesDao()}
)

// Add your custom methods and functionality below.
