// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"claude-test/internal/dao/internal"
)

// gamePlayersDao is the data access object for the table game_players.
// You can define custom methods on it to extend its functionality as needed.
type gamePlayersDao struct {
	*internal.GamePlayersDao
}

var (
	// GamePlayers is a globally accessible object for table game_players operations.
	GamePlayers = gamePlayersDao{internal.NewGamePlayersDao()}
)

// Add your custom methods and functionality below.
