// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"claude-test/internal/dao/internal"
)

// gameActionsDao is the data access object for the table game_actions.
// You can define custom methods on it to extend its functionality as needed.
type gameActionsDao struct {
	*internal.GameActionsDao
}

var (
	// GameActions is a globally accessible object for table game_actions operations.
	GameActions = gameActionsDao{internal.NewGameActionsDao()}
)

// Add your custom methods and functionality below.
