// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"claude-test/internal/dao/internal"
)

// handReplaysDao is the data access object for the table hand_replays.
// You can define custom methods on it to extend its functionality as needed.
type handReplaysDao struct {
	*internal.HandReplaysDao
}

var (
	// HandReplays is a globally accessible object for table hand_replays operations.
	HandReplays = handReplaysDao{internal.NewHandReplaysDao()}
)

// Add your custom methods and functionality below.
