// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"claude-test/internal/dao/internal"
)

// handFavoritesDao is the data access object for the table hand_favorites.
// You can define custom methods on it to extend its functionality as needed.
type handFavoritesDao struct {
	*internal.HandFavoritesDao
}

var (
	// HandFavorites is a globally accessible object for table hand_favorites operations.
	HandFavorites = handFavoritesDao{internal.NewHandFavoritesDao()}
)

// Add your custom methods and functionality below.
