// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"claude-test/internal/dao/internal"
)

// potDistributionsDao is the data access object for the table pot_distributions.
// You can define custom methods on it to extend its functionality as needed.
type potDistributionsDao struct {
	*internal.PotDistributionsDao
}

var (
	// PotDistributions is a globally accessible object for table pot_distributions operations.
	PotDistributions = potDistributionsDao{internal.NewPotDistributionsDao()}
)

// Add your custom methods and functionality below.
