// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"claude-test/internal/dao/internal"
)

// potWinnerDetailsDao is the data access object for the table pot_winner_details.
// You can define custom methods on it to extend its functionality as needed.
type potWinnerDetailsDao struct {
	*internal.PotWinnerDetailsDao
}

var (
	// PotWinnerDetails is a globally accessible object for table pot_winner_details operations.
	PotWinnerDetails = potWinnerDetailsDao{internal.NewPotWinnerDetailsDao()}
)

// Add your custom methods and functionality below.
