// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"claude-test/internal/dao/internal"
)

// roomSessionsDao is the data access object for the table room_sessions.
// You can define custom methods on it to extend its functionality as needed.
type roomSessionsDao struct {
	*internal.RoomSessionsDao
}

var (
	// RoomSessions is a globally accessible object for table room_sessions operations.
	RoomSessions = roomSessionsDao{internal.NewRoomSessionsDao()}
)

// Add your custom methods and functionality below.
