// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"claude-test/internal/dao/internal"
)

// sessionPlayersDao is the data access object for the table session_players.
// You can define custom methods on it to extend its functionality as needed.
type sessionPlayersDao struct {
	*internal.SessionPlayersDao
}

var (
	// SessionPlayers is a globally accessible object for table session_players operations.
	SessionPlayers = sessionPlayersDao{internal.NewSessionPlayersDao()}
)

// Add your custom methods and functionality below.
