// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"claude-test/internal/dao/internal"
)

// tableSeatsDao is the data access object for the table table_seats.
// You can define custom methods on it to extend its functionality as needed.
type tableSeatsDao struct {
	*internal.TableSeatsDao
}

var (
	// TableSeats is a globally accessible object for table table_seats operations.
	TableSeats = tableSeatsDao{internal.NewTableSeatsDao()}
)

// Add your custom methods and functionality below.
