// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"claude-test/internal/dao/internal"
)

// tablesDao is the data access object for the table tables.
// You can define custom methods on it to extend its functionality as needed.
type tablesDao struct {
	*internal.TablesDao
}

var (
	// Tables is a globally accessible object for table tables operations.
	Tables = tablesDao{internal.NewTablesDao()}
)

// Add your custom methods and functionality below.
