// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"claude-test/internal/dao/internal"
)

// tableMessagesDao is the data access object for the table table_messages.
// You can define custom methods on it to extend its functionality as needed.
type tableMessagesDao struct {
	*internal.TableMessagesDao
}

var (
	// TableMessages is a globally accessible object for table table_messages operations.
	TableMessages = tableMessagesDao{internal.NewTableMessagesDao()}
)

// Add your custom methods and functionality below.
