// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"claude-test/internal/dao/internal"
)

// tableObserversDao is the data access object for the table table_observers.
// You can define custom methods on it to extend its functionality as needed.
type tableObserversDao struct {
	*internal.TableObserversDao
}

var (
	// TableObservers is a globally accessible object for table table_observers operations.
	TableObservers = tableObserversDao{internal.NewTableObserversDao()}
)

// Add your custom methods and functionality below.
