// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"claude-test/internal/dao/internal"
)

// tableInvitationsDao is the data access object for the table table_invitations.
// You can define custom methods on it to extend its functionality as needed.
type tableInvitationsDao struct {
	*internal.TableInvitationsDao
}

var (
	// TableInvitations is a globally accessible object for table table_invitations operations.
	TableInvitations = tableInvitationsDao{internal.NewTableInvitationsDao()}
)

// Add your custom methods and functionality below.
