// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"claude-test/internal/dao/internal"
)

// tournamentsDao is the data access object for the table tournaments.
// You can define custom methods on it to extend its functionality as needed.
type tournamentsDao struct {
	*internal.TournamentsDao
}

var (
	// Tournaments is a globally accessible object for table tournaments operations.
	Tournaments = tournamentsDao{internal.NewTournamentsDao()}
)

// Add your custom methods and functionality below.
