// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"claude-test/internal/dao/internal"
)

// userStatsDao is the data access object for the table user_stats.
// You can define custom methods on it to extend its functionality as needed.
type userStatsDao struct {
	*internal.UserStatsDao
}

var (
	// UserStats is a globally accessible object for table user_stats operations.
	UserStats = userStatsDao{internal.NewUserStatsDao()}
)

// Add your custom methods and functionality below.
