// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"claude-test/internal/dao/internal"
)

// userWalletsDao is the data access object for the table user_wallets.
// You can define custom methods on it to extend its functionality as needed.
type userWalletsDao struct {
	*internal.UserWalletsDao
}

var (
	// UserWallets is a globally accessible object for table user_wallets operations.
	UserWallets = userWalletsDao{internal.NewUserWalletsDao()}
)

// Add your custom methods and functionality below.
